-- P14: the demo seed data that used to live in this file (17 places across
-- 8 Hyderabad neighbourhoods, lifted verbatim from the design handoff's
-- prototype — see git history for the previous contents) is retired.
--
-- Discovery has been 100% live Google Places since Phase 8 §5 — nothing a
-- searching user sees was ever decided by a row in this file. What it did
-- still feed was the marketing/SEO pages, a fixed 8-neighbourhood quick-pick
-- on the area-picker, and a catalogue-only ranking flow (S25-S27, since
-- removed) — all now either rebuilt on live data or retired outright. See
-- PHASE_14 planning notes for the full accounting.
--
-- This file is intentionally left with no inserts, rather than deleted: the
-- Supabase CLI's `supabase db reset` expects it to exist. `categories` and
-- `areas` now start empty in a fresh environment; real rows accrue from
-- actual use (live-searched areas, ranked Google places) instead of a fixed
-- demo set. `app_config`'s tunable settings live in their own schema
-- migration (20260820100200_areas_categories_config.sql), not here, and are
-- unaffected by this change.
